version: "3.8"

services:
  api:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      MONGODB_URI: mongodb+srv://yashmanek2001_db_user:aTib6nMQchAfoPKX@cluster0.tuv8tgy.mongodb.net/?appName=Cluster0
      PORT: 3000
      JWT_SECRET: YashManek@2005!
      REDIS_URL: rediss://red-d4097qf5r7bs73a9j3h0:P9JAt6Ne4hfmPtHXj5K6jY8t0KJuMa2c@singapore-keyvalue.render.com:6379
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      args:
        REACT_APP_API_URL: /api/v1 # Use relative path for proxying or direct container access
    ports:
      - "3001:80" # Map host port 3001 to container port 80 (nginx default)
    depends_on:
      - api
    restart: unless-stopped
